In [1]:
import numpy as np

### Create tensor

$$
\begin{bmatrix}  
    \begin{bmatrix}  
        23 & 50 \\   7 & 12 \\  
    \end{bmatrix}  
    \begin{bmatrix}  
        57 & 67 \\   99 & 43  
    \end{bmatrix} \\   
    \begin{bmatrix}  
        75 & 21 \\   57 & 12 \\  
    \end{bmatrix}  
    \begin{bmatrix}  
        87 & 26 \\  18 & 84  
    \end{bmatrix}  
\end{bmatrix}
$$


In [2]:
tensor_4d = np.array(
    [
        [
            [[23, 50], [7, 12]],
            [[57, 67], [99, 43]]
        ],
        [
            [[75, 21], [57, 12]],
            [[87, 26], [18, 84]]
        ]
    ]
)

print(tensor_4d)

[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


### Matrix Multiplication

$$
A =
\begin{bmatrix}
23 & 50 & 19 \\
7 & 12 & 109 \\
57 & 67 & 98
\end{bmatrix}
\begin{bmatrix}
17 \\
22 \\
19
\end{bmatrix}
$$

In [3]:
B = np.array(
    [
        [23, 50, 19],
        [7, 12, 109],
        [57, 67, 98]
    ]
)

A = B @ np.array([17, 22, 19])

print(f'A is {A}')

A is [1852 2454 4305]


### Transpose, Calculate determinant, and Invert

$$
\begin{bmatrix}
23 & 50 & 19 \\
7 & 12 & 109 \\
57 & 67 & 98
\end{bmatrix}
$$

In [4]:
B = np.array(
    [
        [23, 50, 19],
        [7, 12, 109],
        [57, 67, 98]
    ]
)

print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


#### Transpose

In [5]:
print(B.T)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


#### Determinant

In [6]:
print(np.linalg.det(B))

131344.0000000002


#### Inverse

In [7]:
print(np.linalg.inv(B))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
